### ISSUE TITLE
how to forecast next year or month value

### ISSUE THREAD

**Issue by weidongzhou1994** [luis-fernandezt/R-interface-to-X13-ARIMA#1]
as title, I want to predict next year or month's value, but I don't know how to do it. When I us the forecast package, it displays:'list' object cannot be coerced to type 'double'.
 
![image](https://user-images.githubusercontent.com/40510496/87635723-1cb45180-c772-11ea-9719-6092463f2410.png)

**Comment by luis-fernandezt** [comment]
Sorry, but I am not working with library(forecast). But I recommend to you, visit the development page of this package in [https://github.com/robjhyndman/forecast](https://github.com/robjhyndman/forecast) Okay, good luck.
